config/routes.rb
Rails.application.routes.draw do

  devise_for :players

  resources :games

  get 'lobby/index'

  root to: 'lobby#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	# test 3
	def create 
		# hack to coerce JSON.dump to create an array with one object
		temp_list = Array.new(0)
		init_player_list = JSON.dump (temp_list)
		@game = Game.new(state:1,player_list:init_player_list)
		@game.save
		current_player.update_attributes(:available => false)
		redirect_to @game
	end

	def show
		@game = Game.find(params[:id])
		if (@game.state == 1)
			@cur_plist = JSON.parse (@game.player_list)
			@added_player = player_join(@cur_plist,current_player.email)
			@game.update_attributes(player_list:JSON.dump(@added_player))
			current_player.update_attributes(:game_id => @game.id)
		    @players = Player.where(['game_id = ?', @game.id])
		elsif (@game.state < 6)
			@cur_plist = JSON.parse (@game.player_list)
	  		@players = Player.where(['game_id = ?', @game.id])
	  		if (@game.state >= 2)&&(@cur_plist.find_index(current_player.email)!= nil)
	  			@is_turn = your_turn(@cur_plist,@game.current_turn)
	  			@current_turn = @cur_plist[@game.current_turn-1]
	  			@last_turn = last_move(@game)
	  			@bull = @game.bs
	  			@can_call = can_call_bs(current_player.email,@game)
	  			@can_counter = can_counter(@can_call,@game.state,@game)
	  			@targ = @game.target
	  			if (@game.state == 2)&&(@is_turn)
	  				@poss_moves = possible_moves(@game)
	  			elsif (@game.state == 5)&&(@is_turn)
	  				all_cards =  @game.drawn+current_player.my_card
	  				@cards_drawn = ambs_combo(all_cards,current_player.my_card.length,[])
	  			end
	  		end
	  	else
	  		@winner = JSON.parse(@game.player_list)[0]
	  	end
	end

	def possible_moves(g)
		p_list = JSON.parse(g.player_list)
		index = p_list.find_index(current_player.email)
		coins = JSON.parse(g.coin_list)[index]
		temp_list = []
		count = 0
		COST_FOR_MOVES.each do |cost|
			if cost<=coins
				temp_list.push(MOVE_LIST[count])
				count = count + 1
			else
				count = count +1
			end
		end
		return temp_list
	end

	def ambs_combo (cards,num,list)
		if (cards.length == 0)
			return list
		else 
			range_end = cards.length - 1
			first = cards[0..0]
			subcards = cards.slice(1..range_end)
			list_cards = list
			if (num == 2)
				subcards.chars.each do |c|
					list_cards.push(first+c)
				end
				return ambs_combo(subcards,num,list_cards)
			else 				
				return ambs_combo(subcards,num,list_cards)
			end
		end
	end

	def update 
		@game = Game.find(params[:id])
		cur_plist = JSON.parse (@game.player_list)
		if ((cur_plist.length > 0)&&@game.state<2)
			init_game(@game)
			redirect_to @game
		elsif params[:move] && (@game.state == 2)
			update_move(params[:move],params[:target],@game)
			@game.update_attributes(:bs => check_bs(cur_plist,@game.state,@game))
			if (skip_steps(@game))
				handle_move_1(@game,@game.target)	
				end_turn(@game)
				redirect_to @game
			else
				@game.update_attributes(:state => 3)
				redirect_to @game
			end
			
		elsif (@game.state == 3) 
			#calling bs
			#process the effect of move
			if params[:block]&&(params[:block] != "nothing")&&(params[:block] != "called")
				add_blocker(params[:block],@game)
				@game.update_attributes(:final_t => @game.target)
				@game.update_attributes(:target => cur_plist[@game.current_turn-1])
				@game.update_attributes(:state => 4)
				@game.update_attributes(:bs => check_bs(cur_plist,@game.state,@game))
				redirect_to @game
			elsif params[:block] == "called"
				#check if bs call was correct
				handle_bluff(@game,current_turn_player(@game),current_player)
			else 
				check_all_called(@game)
			end
		elsif (@game.state == 4)&&params[:block]
				if params[:block] == "called"
					handle_bluff_4(@game,current_player,current_turn_player(@game))
				else 
					end_turn(@game)
					redirect_to @game
				end
		elsif (@game.state == 5)&&params[:chosen]
			picked = params[:chosen]
			exchange(@game,picked,string_diff(@game,picked))
			end_turn(@game)
			redirect_to @game
		#put a warning to have at least 2 players
		end
	end 

	def remove_defeated(g)
		plist = JSON.parse(g.player_list)
		temp_list = []
		plist.each do |p|
 			temp_p = Player.where(['email = ?', p])[0]
 			if (temp_p.my_card.length != 0)
 				temp_list.push(temp_p.email)
 			end
		end
		#if (temp_list.length == 1)
			#g.update_attributes(:player_list => JSON.dump(temp_list))
		#else
		g.update_attributes(:player_list => JSON.dump(temp_list))
		#end
	end

	def check_all_called(g)
		upd_num = g.moves_made + 1
		g.update_attributes(:moves_made => upd_num)
		if all_moved(g)	
			handle_move_1(g,g.target)	
			post_step(g)
		else
			redirect_to g
		end
	end

	def post_step(g)
		if (g.ambs)&&(g.state == 3)
			g.update_attributes(:state => 5)
			redirect_to g
		else
			end_turn(g)
			redirect_to g
		end
	end

	def handle_move_1(g,target) 
		if (g.state == 4)&&(g.contessa)
			assasinate(g,target)
		elsif (g.state == 4)&&((g.cap)||(g.ambs))
			steal(g,target)
		elsif (g.state ==4)&&(g.duke)
			foreign_aid(g)
		elsif g.assas
			assasinate(g,target)
		elsif g.duke
			tax(g)
		elsif g.fa
			foreign_aid(g)
		elsif g.ambs
			ambs_draw(g)
		elsif g.coup
			coup(g,target)
		elsif g.cap
			steal(g,target)
		elsif g.inc
			income(g)
		end
	end

	def handle_bluff_4(g,p1,p2)
		if has_cards(g,p1.email)
			random_delete(p2)
			end_turn(g)
			redirect_to g				
		else
			random_delete(p1)
			handle_move_1(g,g.final_t)
			end_turn(g)
			redirect_to g
		end	
	end

	def ambs_draw (g)
		upd_string = g.cards
 		p = current_turn_player(g)
		cards = upd_string.slice!(0,p.my_card.length)
		g.update_attributes(:cards => upd_string)
		g.update_attributes(:drawn => cards)
	end

	def string_diff (g,choice)
		switched_out = g.drawn+current_player.my_card
		choice.chars.each do |c|
			index = switched_out.index(c)
			switched_out = switched_out[0,index]+switched_out[index+1..switched_out.length-1]
		end
		return switched_out
	end

	def exchange (g,choice,discard)
		upd_deck = string_shuffle(g.cards+discard)
		g.update_attributes(:cards => upd_deck)
		current_turn_player(g).update_attributes(:my_card => choice)
	end

	def assasinate (g,target)
 		p = Player.where(['email = ?', target])[0]
 		upd_coins = g.coin_list
 		update_coin_list(g,3,current_turn_player(g).email,false)
 		random_delete(p)
	end

	def update_coin_list(g,num,target,isadd)
		coins = JSON.parse(g.coin_list)
		target_index = JSON.parse(g.player_list).find_index(target)
		count = 0
		upd_list = []
		coins.each do |i|
			value = Integer(i)
			if (target_index == count)
				count = count + 1
				if isadd
					value = value + num
					upd_list.push(value)
				else
					value = value - num
					upd_list.push(value)
				end
			else
				count = count + 1
				upd_list.push(value)
			end
		end
		string_form = JSON.dump(upd_list)
		g.update_attributes(:coin_list => string_form)
	end

	def tax (g)
 		upd_coins = g.coin_list
 		update_coin_list(g,3,current_turn_player(g).email,true)
	end

	def income (g)
 		upd_coins = g.coin_list
 		update_coin_list(g,1,current_turn_player(g).email,true)
	end 

	def foreign_aid (g)
 		upd_coins = g.coin_list
 		update_coin_list(g,2,current_turn_player(g).email,true)	
	end 

	def steal (g,target)
		cur_plist = JSON.parse(g.player_list)
 		upd_coins = g.coin_list
 		targ_index = cur_plist.find_index(target)
 		targ_coins = JSON.parse(g.coin_list)[targ_index]
 		if (targ_coins < 2)
 			update_coin_list(g,targ_coins,target,false)
 			update_coin_list(g,targ_coins,current_turn_player(g).email,true)
 		else 
 			 update_coin_list(g,2,target,false)
 			update_coin_list(g,2,current_turn_player(g).email,true)
 		end
	end 

	def coup(g,target)
 		p = Player.where(['email = ?', target])[0]
 		upd_coins = g.coin_list
 		update_coin_list(g,7,current_turn_player(g).email,false)
 		random_delete(p)
	end

	def handle_bluff(g,p1,p2)
		if has_cards(g,p1.email)
			random_delete(p2)				
			handle_move_1(g,g.target)
			post_step(g)
		else
			random_delete(p1)
			end_turn(g)
			redirect_to g
		end	
	end

	def random_delete(p)
		cards = p.my_card
		sliced = ""
		if cards.length == 1
			p.update_attributes(:my_card => "")
		elsif cards.length != 0
			sliced = cards[0,1]
			p.update_attributes(:my_card => sliced)
		else
			p.update_attributes(:my_card => "")
		end
	end

	def current_turn_player(g)
		temp_list = JSON.parse(g.player_list)
		name = temp_list[g.current_turn-1]
 		p = Player.where(['email = ?', name])[0]
 		return p
 	end	

	def has_cards(g,name)
 		p = Player.where(['email = ?', name])[0]
 		cards = p.my_card.scan(/./)
		if g.assas&&(cards.find_index('x')!= nil)
			return true
		elsif g.duke&&(cards.find_index('d')!= nil)
			return true
		elsif g.ambs&&(cards.find_index('a')!= nil)
			return true
		elsif g.cap&&(cards.find_index('c')!= nil)
			return true
		elsif g.contessa&&(cards.find_index('l')!= nil)
			return true
		else
			return false
		end
	end



	#do cur_plist.length - 1 after locking the player himself 
	def all_moved (g)
		cur_plist = JSON.parse(g.player_list)
		if g.moves_made >= cur_plist.length
			return true
		else 
			return false
		end
	end

	#game state functions 

	##helper functions

	def end_turn (g)
		remove_defeated(g)
		if (JSON.parse(g.player_list).length <= 1)
			clear_moves(g)
			g.update_attributes(:state => 6)
		else
			cur_plist = JSON.parse (g.player_list)
			clear_moves(g)
			update_turn = next_turn(cur_plist,g.current_turn)
			g.update_attributes(:current_turn => update_turn)
			g.update_attributes(:state => 2)
		end
	end

	def make_hand (p,deck)
		play = Player.where(['email = ?', p])[0]
		cards = deck.pop()
		cards = cards + deck.pop()
		play.update_attributes(:my_card => cards)
	end
	def init_game(g)
		cur_plist = JSON.parse (@game.player_list)
		clear_moves(g)
		g.update_attributes(:state => 2)
		shuffled = string_shuffle(CARDS)
		deck_list = shuffled.scan(/./)
		coin_list = Array.new(cur_plist.length,2)
		g.update_attributes(:coin_list => JSON.dump(coin_list))
		cur_plist.map { |p| make_hand(p,deck_list) }
		g.update_attributes(:cards => list_to_string(deck_list))
		cur_plist.shuffle!

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/_ambs_selection.html.erb
<%= form_tag game_path(@game.id), :method => 'put' do %>
  <table>
    <tr>
      <th>moves</th>
      <th colspan ="1"></th>
    </tr>
    <% if (@game.ambs)&&(@is_turn) %>
      <% @cards_drawn.each do |c| %>
      <tr>
        <td><%= radio_button_tag(:chosen, c) %></td>
        <td><%= label_tag(:move_detail, "chose hand " + c) %></td>
      </tr>
      <% end %>
    <% end %>
  </table>
  <%= submit_tag "make move", {:name => nil} %>
<% end %>

app/views/games/_countering_form.html.erb
<%= form_tag game_path(@game.id), :method => 'put' do %>
  <table>
    <tr>
      <th>moves</th>
      <th colspan ="1"></th>
    </tr>
    <% if (@can_call)&&(not @is_turn) %>
      <tr>
        <td><%= radio_button_tag(:block, "called") %></td>
        <td><%= label_tag(:move_detail, "call bluff on " + @last_turn) %></td>
      </tr>
    <% end %>
    <% if (@can_counter)&&(@game.cap) %>
      <tr>
        <td><%= radio_button_tag(:block, "captain") %></td>
        <td><%= label_tag(:move_detail, "block " + @last_turn + " with captain") %></td>
      </tr>
      <tr>
        <td><%= radio_button_tag(:block, "ambs") %></td>
        <td><%= label_tag(:move_detail, "block "+ @last_turn + " with ambassador") %></td>
      </tr>
    <% elsif (@can_counter) %>
      <tr>
        <td><%= radio_button_tag(:block, "block") %></td>
        <td><%= label_tag(:move_detail, "block his move " + @last_turn) %></td>
      </tr>    
    <% end %>
    <tr> 
      <td><%= radio_button_tag(:block, "nothing") %></td>
      <td><%= label_tag(:move_detail, "do nothing against " + @last_turn) %></td>
     </tr>
  </table>
  <%= submit_tag "make move", {:name => nil} %>
<% end %>

app/views/games/_player_table.html.erb
<table>
  <tr>
    <th></th>
  </tr>
 
  <% @cur_plist.each do |user| %>
    <tr>
      <td><%= user %></td>
    </tr>
  <% end %>
</table>

app/views/games/_possible_moves.html.erb
<%= form_tag game_path(@game.id), :method => 'put' do %>
  <table>
    <tr>
      <th>moves</th>
      <th colspan ="1"></th>
    </tr>
    <% @poss_moves.each do |moves| %>
    <tr>
      <td><%= radio_button_tag(:move, moves) %></td>
      <td><%= label_tag(:move_detail, moves) %></td>
    </tr>
    <% end %>
    <tr>
      <td>target</td>
      <td><%= select_tag(:target,options_for_select(@cur_plist)) %></td>
    </tr>
  </table>
  <%= submit_tag "make move", {:name => nil} %>
<% end %>

app/views/games/_pre_winner.html.erb
<p>
<li> Players/Cards </li>
<% @players.each do |p| %>
  <%= p.email %>
  <%= "has cards " + p.my_card %>
<% end %>
</p>

<% if @game.state < 2 %>
  <%= button_to 'update', game_path, method: 'patch' %>
<% end %>

<% if @game.state >= 3 %>
  <li><%= "the last move was "+ @last_turn %></li>
  <li><%= @bull %></li>
  <li><%= "the target is " %></li>
  <li><%= @game.current_turn %></li>
  <li><%= "cards in deck " + @game.cards %></li>
  <li><%= @game.coin_list %></li>
<% end %>


<% if @game.state == 2 && @is_turn == true %>
  <li><%= "the last move was "+ @last_turn %></li>
  <li><%= "cards in deck " + @game.cards %></li>
  <li><%= @game.coin_list %></li>
  <%= render 'possible_moves' %>
<% end %>

<% if (@game.state == 3)||(@game.state == 4) %>
  <%= render 'countering_form' %>
<% end %>

<% if (@game.state == 5) %>
  <%= render 'ambs_selection' %>
<% end %>

app/views/games/show.html.erb
<p>
	<%= 'Game '+ String(@game.id) %>
</p>

<%= @game.state %>
<% if @game.state < 6 %>
  <h3>Players In Game</h3>
  <%= render 'player_table' %>

  <%= render 'pre_winner' %>
<% else %>
  <li><%= "The winner is " + @winner %></li>
<% end %>

<p><%= link_to 'Back', lobby_index_path %></p>